FROM node:22-alpine

WORKDIR /app

# Dependencies install (sirf package.json se)
COPY package.json package-lock.json ./
RUN npm install

# Code ko mount karenge, isliye yahan copy nahi kar rahe
EXPOSE 3000

CMD ["npm", "run", "dev"]
